name: WakaTime Stats

on:
  push:  # プッシュ時にワークフローを実行する
    branches:
      - main  # メインブランチに限定する（必要に応じて変更可能）

jobs:
  wakatime:
    runs-on: self-hosted  # ローカル開発環境を使用する場合

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # リポジトリのチェックアウトを行う

      - name: Set up Python
        uses: actions/setup-python@v2  # Pythonのセットアップを行う
        with:
          python-version: 3.x  # 使用するPythonのバージョンを指定

      - name: Install WakaTime CLI
        run: pip install wakatime  # WakaTime CLIをインストールする

      - name: Fetch WakaTime Stats
        run: wakatime --config ~/.wakatime.cfg --today > wakatime_stats.txt  # WakaTimeの統計情報を取得し、テキストファイルに出力する

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"  # コミット用のユーザー情報を設定
          git config --local user.name "GitHub Action"
          git add wakatime_stats.txt  # ファイルの追加をステージング
          git commit -m "Update WakaTime stats"  # コミット
          git push  # プッシュ
